# Generated by Django 5.2.4 on 2025-07-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['data_start']},
        ),
    ]
