# Generated by Django 5.2.4 on 2025-07-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['id']},
        ),
    ]
