# Generated by Django 5.2.4 on 2025-07-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date_start']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='data_end',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='data_start',
            new_name='date_start',
        ),
    ]
