# Generated by Django 5.2.4 on 2025-07-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_booking_date_end_alter_booking_date_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='creation_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='creation_time',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
